### ISSUE TITLE
이미지 API를 개선합니다.

### ISSUE THREAD

**Issue by DongGeon0908** [depromeet/toks-api#117]
현재 이미지 업로드 API가 단건 이미지만 업로드 가능한데, 다수의 이미지를 업로드할 수 있도록 고도화 합니다.
1. 한번에 10개의 이미지가 업로드되도록 구현
2. 이미지에 대한 사이즈, 개수 등의 유효성 체크 필요
3. 이미지 업로드를 한 이유에 대해서도 기록될 수 있도록 개선

**Comment by SieunKiim** [comment]
지구가 움직이기 시작했다 🏃‍♀️

**Comment by SieunKiim** [comment]
> 현재 이미지 업로드 API가 단건 이미지만 업로드 가능한데, 다수의 이미지를 업로드할 수 있도록 고도화 합니다.
> 
> 1. 한번에 10개의 이미지가 업로드되도록 구현
> 2. 이미지에 대한 사이즈, 개수 등의 유효성 체크 필요
> 3. 이미지 업로드를 한 이유에 대해서도 기록될 수 있도록 개선

@DongGeon0908 동건님 저희가 이미지 업로드는 퀴즈 생성 경우 밖에 없는 것으로 알고있는데 혹시 3번 이유가 궁금합니다!!
- 추후 이미지 업로드 로직이 추가될 수도 있다..?
- 업로드된 이미지의 정확한 정보를 기록한다..?( {quizId}퀴즈의 {n}번째 사진이다 )

**Comment by DongGeon0908** [comment]
@SieunKiim 
제가 요청 드린 사항은 해당 이미지 API의 모듈화입니다!
앞으로 어떤 요청이 들어올지 모르는 상황에서 로깅 추적 혹은 유효성 검사를 하기 위함입니다!
엄청 자세하게 할 필요는 없고, 해당 이미지 업로드 요청은 퀴즈 생성으로 부터 발현되었다 정도의 내용만 담아도 괜찮을 것 같아요
