### ISSUE TITLE
태그 입력 고도화 작업을 진행한다

### ISSUE THREAD

**Issue by DongGeon0908** [depromeet/toks-api#118]
현재 태그 입력시, 계속 모든 태그 정보에 대해서 조회하고 id 값을 매핑하는데,
해당 부분은 DB 부하 및 불필요한 매핑이라고 생각합니다 (현 상황에서)

AS-IS
- 스터디 요청시 태그의 유무 파악하고 태그 삽입 진행
- 모든 태그에 대한 조회 작업 진행

TO-BE
- 태그 정보를 스터디 테이틀의 특정 컬럼에 모두 삽입
- 모든 태그 정보를 큐에 삽입하여 저장 진행
- 태그를 비교하는 작업을 삭제
- 추후 태그 사전을 도입하여 인덱싱 진행

cc. @SieunKiim @hocaron @south-daria

**Comment by DongGeon0908** [comment]
Queue 기반 이벤트 처리로 해당 작업을 수행하겠습니다.

**Comment by DongGeon0908** [comment]
끝

**Comment by DongGeon0908** [comment]
- 이벤트 시스템 기반으로 진행
- 기존 테이블 로직은 그대로 수행

**Comment by SieunKiim** [comment]
> * 이벤트 시스템 기반으로 진행
> * 기존 테이블 로직은 그대로 수행

~~아..! 지금 "태그 정보를 스터디 테이블 특정 칼럼에 삽입"이 어디서 이루어지는지 여쭤보려 했는데 😅~~

아 요건 제가 잘못 보고 있었네요, 맨 위에 커밋만 보고 있어서 수정 내용을 온전히 보지 못했습니다..!

![image](https://user-images.githubusercontent.com/39111133/218302004-cc8b4c38-c108-43e9-81cc-6da90e3fea1c.png)

**Comment by SieunKiim** [comment]
@DongGeon0908
추가로 이벤트 시스템 기반 작업들을 찾아 보면서 이해해보려 하는데요, 혹시 기존 방식에서 지금과 같은 Queue 방식으로 변경했을 때, 가지는 장점이 있는지 궁금합니다!

제가 이해한 변경 내용이, 스터디 생성 시 태그들을 DB에 저장하는 과정을 분리한게 맞을까요..?

> 여러개의 스터디가 생성될 때 각각 태그 저장 로직들을 Event Driven으로 큐에 저장해서, 성능 향상을 생각해볼 수 있는건가요?

**Comment by DongGeon0908** [comment]
넵넵 맞습니다.
즉시 태그가 생성되지 않고, Queue에 저장한 다음에, 순차적으로 진행을 하는 방식으로 변경했어요.

**Comment by SieunKiim** [comment]
오호 딱 알았습니다 감사합니다!
더 공부해볼게용
