### ISSUE TITLE
퀴즈 문제 풀이 결과에 대한 count caching 처리

### ISSUE THREAD

**Issue by DongGeon0908** [depromeet/toks-api#188]
DB에서 직접 조회하는 방식이 아니라, 캐싱을 통한 count 처리

**Comment by SieunKiim** [comment]
요게 하루에 퀴즈 몇개 풀었는지 확인하는 API 관련된게 맞을까요?

**Comment by DongGeon0908** [comment]
@SieunKiim 
앗 아니요!
특정 문제의 답안 수를 보요주는 기능이에요!
현재는 전부 count query로 제공하고 있어요.

**Comment by DongGeon0908** [comment]
DB 부하를 줄 수 있는 것들이라, 수정해야 될 것 같아요!
@SieunKiim 
원하시는 작업 있으면 어사인 바꾸셔서 작업 진행하시면 될 것 같아요!

**Comment by DongGeon0908** [comment]
@SieunKiim 
이거 보니까, 원래 기능 없었는데, 제가 비동기로 구현해두었어요.
일단, 배포하고, 문제되면 캐시 바르져
