### ISSUE TITLE
FAB - 사용자의 퀴즈 풀이 히스토리 내역 정보를 제공한다.

### ISSUE THREAD

**Issue by DongGeon0908** [depromeet/toks-api#195]
**이번달**
- history table을 직접 조회하여 제공한다.
- db 조회 진행후, 몇분간 캐싱 진행

**지난달**
- 매월 1일 지난달 기록에 대한 히스토리를 스냅샷으로 기록한다. (조회를 빠르게 하기 위함)
- 배치성 로직이어야 함
- uid, 일별 푼 quizHistoryId 등등을 기록 (데이터가 없는 경우, 기록X)

조금 더 좋은 방법이 있다면, 말씀해주세요!

**Comment by SieunKiim** [comment]
몇가지 궁금한 점들이 있는데요!
1. history table 이라는게 기존 "quiz_reply_history" 테이블 말씀하는게 맞을지요?
2. 스트릭 기능을 제공하는 것으로 알고있는데, 그럼 조회 시 마다, 오늘 기준으로 "quiz_reply_history" 테이블에서 몇 일간 연속으로 제출했는지 항상 연산해야하는걸까요? (캐싱 이후에)

**Comment by DongGeon0908** [comment]
1. 기존 기록 테이블 말고, user의 통계 정보를 저장하는 별도의 테이블이 있어야 할 것 같아요. (SNAPSHOT용)
2. 넵넵, quiz_reply_history에서 uid와 요일을 기반으로 데이터 조회하고, 연속 제출 기간을 계산해서 제공하면 될 것 같아요.

2번의 경우가 조회시 문제가 될까? 라는 고민을 좀 했는데, uid indexing 걸고 요일 한정지어서 조회하면 문제되지는 않을 것 같아요.
서버에서 계산하는 동작은 부하가 거의 없는 동작이라 문제될 것 같지도 않구용

**Comment by SieunKiim** [comment]
동건님 혹시 괜찮으시면 내일 잠깐 저녁에 회의 어떠신가요!?
텍스트로 확! 와닿지 않기도 하고 중간중간 궁금한 부분들도 있고 해서 한번 말씀드려 봅니다
오늘은, 내일 5시 반 기상 이슈로 쪼오금 여러울 듯 하고, 내일 퇴근할 때 한번 연락 남겨두겠습니다..! 🙇🏻‍♂️

내일 괜찮으시다면 편한 시간 남겨주셔도 좋습니다..!

**Comment by DongGeon0908** [comment]
@SieunKiim 
해당 작업은 완료되었다고 판단하여, close 하겠습니다.
