### ISSUE TITLE
똑순위 계산 방식 반영

### ISSUE THREAD

**Issue by hocaron** [depromeet/toks-api#78]
### 똑순위 변경된 계산 방식 반영
- 득표수를 순위에 그대로 반영하는 똑순위 계산 방식을 반영합니다.
- 답변 좋아요 API 호출 시에 해당 답변 작성자의 score를 1증가 시킵니다.

### 퀴즈의 최고 점수를 출제자에 점수에 반영하는 방식 논의 필요
- 스프링 쿼츠
- 간단한 스케줄러

**Comment by hocaron** [comment]
@depromeet/12th-team-5-backend 똑순위 투표개수의 최대값을 출제자에게도 부여하는 방식에 대한 논의가 필요합니다.
fyi; [변경된 점수 계산 방식에 대한 스레드](https://5gaeanmal.slack.com/archives/C044R1B6526/p1671629869080669)

제가 생각한 방식은 퀴즈 끝나는 시간에 스케줄러 예약해서, 퀴즈에서 제일 많이 받은 득표수를 출제자에게도 부여하는 방식입니다.

**Comment by SieunKiim** [comment]
스케줄러에 예약한다는게 프론트에서 퀴즈 끝나는 시간에 보내주는건가요..? 🤔

출제자에게 투표 개수의 최대값 (최대 점수)를 부여하는 방식은 좋은 것 같아요!! 👍👍

피그마에 선우님이 말씀해주신 등수 별로 1, 2, 3등에게 각 3점,2점,1점을 부여하는 방식에서 투표 갯수로 확정된 이유가 있을지 궁금합니다..!
말씀해주신 득표 수의 경우 회차마다 투표 양에 따른 오차를 배제하게 된걸까요..? ☺️

**Comment by hocaron** [comment]
> 스케줄러에 예약한다는게 프론트에서 퀴즈 끝나는 시간에 보내주는건가요..? 🤔
> 
> 출제자에게 투표 개수의 최대값 (최대 점수)를 부여하는 방식은 좋은 것 같아요!! 👍👍
> 
> 피그마에 선우님이 말씀해주신 등수 별로 1, 2, 3등에게 각 3점,2점,1점을 부여하는 방식에서 투표 갯수로 확정된 이유가 있을지 궁금합니다..! 말씀해주신 득표 수의 경우 회차마다 투표 양에 따른 오차를 배제하게 된걸까요..? ☺️

1. 제가 생각한 방식은 프론트에서 퀴즈를 만들 때, 퀴즈가 끝나는 시간도 함께 받기 때문에 퀴즈 끝나는 시간에 해당 퀴즈의 최고 투표 갯수를 측정해서 퀴즈 출제자에게 같은 점수를 부여하는 스케줄러를 등록하는 방식이었습니다:) (서버에서만 관리하는 방식입니다. 지금 상황에서 프론트에서 추가적으로 해야하는 작업은 없습니다.)

2. 변경된 이유는 현재는 똑표결과로 우수 답변 1개만 보여주고 있는데, 차등적으로 점수를 부여할 경우(1,2,3 점) 3개의 답변을 보여줘야 하는 프론트 공수가 필요할 것으로 디자이너분들과 이야기가 되었습니다. 저는 개인적으로 차등적으로 점수부여하는 동기부여 측면에서 좋은 것 같아서ㅋㅋㅋㅋㅋㅋ MVC 배포 후에 한번 이야기를 나눠보기로 하였습니다😀 시은님 의견은 어떠신지 궁금합니닷!!

**Comment by SieunKiim** [comment]
> 1. 제가 생각한 방식은 프론트에서 퀴즈를 만들 때, 퀴즈가 끝나는 시간도 함께 받기 때문에 퀴즈 끝나는 시간에 해당 퀴즈의 최고 투표 갯수를 측정해서 퀴즈 출제자에게 같은 점수를 부여하는 스케줄러를 등록하는 방식이었습니다:) (서버에서만 관리하는 방식입니다. 지금 상황에서 프론트에서 추가적으로 해야하는 작업은 없습니다.)
> 2. 변경된 이유는 현재는 똑표결과로 우수 답변 1개만 보여주고 있는데, 차등적으로 점수를 부여할 경우(1,2,3 점) 3개의 답변을 보여줘야 하는 프론트 공수가 필요할 것으로 디자이너분들과 이야기가 되었습니다. 저는 개인적으로 차등적으로 점수부여하는 동기부여 측면에서 좋은 것 같아서ㅋㅋㅋㅋㅋㅋ MVC 배포 후에 한번 이야기를 나눠보기로 하였습니다😀 시은님 의견은 어떠신지 궁금합니닷!!

저도 차등 점수제가 더 좋은데 이러면 동점자 문제가 생겨버리니...
제출 시간을 기준으로 추가 점수를 주면 어떨까요?
문제 풀 수 있는 시간 30분 -> 1800초 중에, 
A 사용자 시작한지 10분(600초) 만에 제출 = 1800 - 600 = 1200 
B 사용자 시작한지 12분(720초) 만에 제출 = 1800 -720  = 1080

A와 B 사용자가 같은 득표수를 갖더라도 억지 등수 나누기 통해서 우수 답변을 하나만 보여줄 수 있도록..? 할 수 있지 않을까...
뭔가 백엔드 공수만 늘어나는 느낌이지만 😂
자기 전에 생각해봤습니당 🛌

ps. 생각해보니 차등제가 아니더라도 동점자 있으면 우수 답변 선정을 어떻게 하죠? 단순히 차등제 이고 아니고의 문제가 아닌가..?
내가 지금 졸린가 싶네용

**Comment by hocaron** [comment]
> > 1. 제가 생각한 방식은 프론트에서 퀴즈를 만들 때, 퀴즈가 끝나는 시간도 함께 받기 때문에 퀴즈 끝나는 시간에 해당 퀴즈의 최고 투표 갯수를 측정해서 퀴즈 출제자에게 같은 점수를 부여하는 스케줄러를 등록하는 방식이었습니다:) (서버에서만 관리하는 방식입니다. 지금 상황에서 프론트에서 추가적으로 해야하는 작업은 없습니다.)
> 
> > 2. 변경된 이유는 현재는 똑표결과로 우수 답변 1개만 보여주고 있는데, 차등적으로 점수를 부여할 경우(1,2,3 점) 3개의 답변을 보여줘야 하는 프론트 공수가 필요할 것으로 디자이너분들과 이야기가 되었습니다. 저는 개인적으로 차등적으로 점수부여하는 동기부여 측면에서 좋은 것 같아서ㅋㅋㅋㅋㅋㅋ MVC 배포 후에 한번 이야기를 나눠보기로 하였습니다😀 시은님 의견은 어떠신지 궁금합니닷!!
> 
> 
> 
> 저도 차등 점수제가 더 좋은데 이러면 동점자 문제가 생겨버리니...
> 
> 제출 시간을 기준으로 추가 점수를 주면 어떨까요?
> 
> 문제 풀 수 있는 시간 30분 -> 1800초 중에, 
> 
> A 사용자 시작한지 10분(600초) 만에 제출 = 1800 - 600 = 1200 
> 
> B 사용자 시작한지 12분(720초) 만에 제출 = 1800 -720  = 1080
> 
> 
> 
> A와 B 사용자가 같은 득표수를 갖더라도 억지 등수 나누기 통해서 우수 답변을 하나만 보여줄 수 있도록..? 할 수 있지 않을까...
> 
> 뭔가 백엔드 공수만 늘어나는 느낌이지만 😂
> 
> 자기 전에 생각해봤습니당 🛌
> 
> 
> 
> ps. 생각해보니 차등제가 아니더라도 동점자 있으면 우수 답변 선정을 어떻게 하죠? 단순히 차등제 이고 아니고의 문제가 아닌가..?
> 
> 내가 지금 졸린가 싶네용

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ엄청난 피드백이다👍👍
지금 문제가 되는게 피그마 페이지에서는 한개의 답변만 보여줄 수 있는데, 여러개의 답변을 보여줘야 하는 경우(차등 점수제) 가 프엔 분들 공수가 필요할 것 같아서 어려울 것 같다는 의견이 있었거든요ㅋㅋㅋ 시은님 말씀대로 동점일 경우에 여러 답변이 보여줘야 하는데 이부분 전달 드러야 겠네용☺️

MVP 배포 후에 점수 계산 방식은 더 논의해봅시당
